
import { Language } from './types';

export const languages: { code: Language; name: string; flag: string }[] = [
    { code: 'en', name: 'English', flag: '🇺🇸' },
    { code: 'es', name: 'Español', flag: '🇪🇸' },
    { code: 'hi', name: 'हिन्दी', flag: '🇮🇳' },
    { code: 'te', name: 'తెలుగు', flag: '🇮🇳' },
    { code: 'fr', name: 'Français', flag: '🇫🇷' },
    { code: 'de', name: 'Deutsch', flag: '🇩🇪' },
    { code: 'zh', name: '中文', flag: '🇨🇳' },
];

export const translations: Record<Language, Record<string, string>> = {
    en: {
        login: 'Login',
        logout: 'Logout',
        homeTitle: 'Fairer Interviews, Better Hires',
        homeSubtitle: 'Our AI-powered platform provides unbiased, structured interviews to help you identify the best talent, free from prejudice.',
        startInterview: 'Start My Interview',
        viewHRDashboard: 'View HR Dashboard',
        feature1Title: 'AI-Powered Questions',
        feature1Desc: 'Generate relevant, role-specific questions that assess skills and experience accurately.',
        feature2Title: 'Unbiased Evaluation',
        feature2Desc: 'Focus on what matters. Our AI provides objective feedback, reducing human bias.',
        feature3Title: 'In-depth Reporting',
        feature3Desc: 'Get detailed reports on candidate performance, with clear metrics and summaries.',
        interviewSetupTitle: 'AI Interview Setup',
        pasteResume: 'Paste your resume text here...',
        jobRolePlaceholder: 'Enter the job role you are applying for...',
        parseResume: 'Analyze Resume & Start',
        analyzing: 'Analyzing your resume...',
        skillsReview: 'Your Skills Review',
        skillsReviewDesc: 'We\'ve analyzed your resume. Please review the skills we identified before starting the interview.',
        interviewInProgress: 'Interview in Progress',
        yourAnswer: 'Type your answer here...',
        interviewComplete: 'Interview Complete!',
        interviewCompleteDesc: 'Thank you for completing the interview. We are generating your detailed report now.',
        role: 'Role',
        candidate: 'Candidate',
        hrAdmin: 'HR / Recruiter',
        accountCreatedSuccess: 'Account created! You can now log in.',
        forgotPassword: 'Forgot Password?',
        resetPassword: 'Reset Password',
        resetPasswordInstruction: 'Enter your email to receive a reset link.',
        sendResetLink: 'Send Reset Link',
        checkEmailForReset: 'Check your email for the reset link.',
        backToLogin: 'Back to Login',
        setNewPassword: 'Set New Password',
        enterNewPassword: 'Enter your new password below.',
        newPassword: 'New Password',
        confirmNewPassword: 'Confirm New Password',
        passwordsDoNotMatch: 'Passwords do not match.',
        passwordUpdatedSuccess: 'Password updated successfully!',
        updatePassword: 'Update Password',
    },
    es: {
        login: 'Iniciar sesión',
        logout: 'Cerrar sesión',
        homeTitle: 'Entrevistas más justas, mejores contrataciones',
        homeSubtitle: 'Nuestra plataforma impulsada por IA proporciona entrevistas estructuradas e imparciales para ayudarle a identificar el mejor talento, libre de prejuicios.',
        startInterview: 'Comenzar mi entrevista',
        viewHRDashboard: 'Ver panel de RR.HH.',
        feature1Title: 'Preguntas impulsadas por IA',
        feature1Desc: 'Genere preguntas relevantes y específicas para el puesto que evalúen las habilidades y la experiencia con precisión.',
        feature2Title: 'Evaluación imparcial',
        feature2Desc: 'Concéntrese en lo que importa. Nuestra IA proporciona comentarios objetivos, reduciendo el sesgo humano.',
        feature3Title: 'Informes detallados',
        feature3Desc: 'Obtenga informes detallados sobre el rendimiento de los candidatos, con métricas y resúmenes claros.',
        interviewSetupTitle: 'Configuración de la entrevista de IA',
        pasteResume: 'Pegue el texto de su currículum aquí...',
        jobRolePlaceholder: 'Ingrese el puesto de trabajo al que se postula...',
        parseResume: 'Analizar currículum y comenzar',
        analyzing: 'Analizando tu currículum...',
        skillsReview: 'Revisión de sus habilidades',
        skillsReviewDesc: 'Hemos analizado su currículum. Revise las habilidades que identificamos antes de comenzar la entrevista.',
        interviewInProgress: 'Entrevista en curso',
        yourAnswer: 'Escribe tu respuesta aquí...',
        interviewComplete: '¡Entrevista completada!',
        interviewCompleteDesc: 'Gracias por completar la entrevista. Estamos generando su informe detallado ahora.',
        role: 'Rol',
        candidate: 'Candidato',
        hrAdmin: 'RR.HH. / Reclutador',
        accountCreatedSuccess: '¡Cuenta creada! Ya puedes iniciar sesión.',
        forgotPassword: '¿Olvidaste tu contraseña?',
        resetPassword: 'Restablecer contraseña',
        resetPasswordInstruction: 'Introduce tu correo electrónico para recibir un enlace de restablecimiento.',
        sendResetLink: 'Enviar enlace de restablecimiento',
        checkEmailForReset: 'Revisa tu correo electrónico para ver el enlace de restablecimiento.',
        backToLogin: 'Volver a iniciar sesión',
        setNewPassword: 'Establecer nueva contraseña',
        enterNewPassword: 'Introduce tu nueva contraseña a continuación.',
        newPassword: 'Nueva contraseña',
        confirmNewPassword: 'Confirmar nueva contraseña',
        passwordsDoNotMatch: 'Las contraseñas no coinciden.',
        passwordUpdatedSuccess: '¡Contraseña actualizada correctamente!',
        updatePassword: 'Actualizar contraseña',
    },
    hi: {
        login: 'लॉग इन करें',
        logout: 'लॉग आउट',
        homeTitle: 'निष्पक्ष साक्षात्कार, बेहतर नियुक्तियाँ',
        homeSubtitle: 'हमारा एआई-संचालित मंच आपको पूर्वाग्रह से मुक्त, सर्वश्रेष्ठ प्रतिभा की पहचान करने में मदद करने के लिए निष्पक्ष, संरचित साक्षात्कार प्रदान करता है।',
        startInterview: 'मेरा साक्षात्कार शुरू करें',
        viewHRDashboard: 'एचआर डैशबोर्ड देखें',
        feature1Title: 'एआई-संचालित प्रश्न',
        feature1Desc: 'प्रासंगिक, भूमिका-विशिष्ट प्रश्न उत्पन्न करें जो कौशल और अनुभव का सटीक आकलन करते हैं।',
        feature2Title: 'निष्पक्ष मूल्यांकन',
        feature2Desc: 'जो मायने रखता है उस पर ध्यान दें। हमारा एआई वस्तुनिष्ठ प्रतिक्रिया प्रदान करता है, जिससे मानवीय पूर्वाग्रह कम होता है।',
        feature3Title: 'गहन रिपोर्टिंग',
        feature3Desc: 'स्पष्ट मैट्रिक्स और सारांश के साथ उम्मीदवार के प्रदर्शन पर विस्तृत रिपोर्ट प्राप्त करें।',
        interviewSetupTitle: 'एआई साक्षात्कार सेटअप',
        pasteResume: 'अपना बायोडाटा टेक्स्ट यहां पेस्ट करें...',
        jobRolePlaceholder: 'आप जिस नौकरी की भूमिका के लिए आवेदन कर रहे हैं उसे दर्ज करें...',
        parseResume: 'बायोडाटा का विश्लेषण करें और शुरू करें',
        analyzing: 'आपके बायोडाटा का विश्लेषण किया जा रहा है...',
        skillsReview: 'आपके कौशल की समीक्षा',
        skillsReviewDesc: 'हमने आपके बायोडाटा का विश्लेषण किया है। साक्षात्कार शुरू करने से पहले कृपया हमारे द्वारा पहचानी गई क्षमताओं की समीक्षा करें।',
        interviewInProgress: 'साक्षात्कार प्रगति पर है',
        yourAnswer: 'अपना उत्तर यहाँ लिखें...',
        interviewComplete: 'साक्षात्कार पूरा हुआ!',
        interviewCompleteDesc: 'साक्षात्कार पूरा करने के लिए धन्यवाद। हम अब आपकी विस्तृत रिपोर्ट तैयार कर रहे हैं।',
        role: 'भूमिका',
        candidate: 'उम्मीदवार',
        hrAdmin: 'एचआर / भर्तीकर्ता',
        accountCreatedSuccess: 'खाता बन गया! अब आप लॉग इन कर सकते हैं।',
        forgotPassword: 'पासवर्ड भूल गए?',
        resetPassword: 'पासवर्ड रीसेट करें',
        resetPasswordInstruction: 'रीसेट लिंक प्राप्त करने के लिए अपना ईमेल दर्ज करें।',
        sendResetLink: 'रीसेट लिंक भेजें',
        checkEmailForReset: 'रीसेट लिंक के लिए अपना ईमेल जांचें।',
        backToLogin: 'लॉगिन पर वापस जाएं',
        setNewPassword: 'नया पासवर्ड सेट करें',
        enterNewPassword: 'नीचे अपना नया पासवर्ड दर्ज करें।',
        newPassword: 'नया पासवर्ड',
        confirmNewPassword: 'नए पासवर्ड की पुष्टि करें',
        passwordsDoNotMatch: 'पासवर्ड मेल नहीं खाते।',
        passwordUpdatedSuccess: 'पासवर्ड सफलतापूर्वक अपडेट किया गया!',
        updatePassword: 'पासवर्ड अपडेट करें',
    },
    te: {
        login: 'లాగిన్ చేయండి',
        logout: 'లాగ్ అవుట్',
        homeTitle: 'న్యాయమైన ఇంటర్వ్యూలు, మంచి నియామకాలు',
        homeSubtitle: 'మా AI- ఆధారిత ప్లాట్‌ఫారమ్ పక్షపాతం లేకుండా, ఉత్తమ ప్రతిభను గుర్తించడంలో మీకు సహాయపడటానికి నిష్పాక్షికమైన, నిర్మాణాత్మక ఇంటర్వ్యూలను అందిస్తుంది.',
        startInterview: 'నా ఇంటర్వ్యూని ప్రారంభించండి',
        viewHRDashboard: 'HR డాష్‌బోర్డ్‌ను వీక్షించండి',
        feature1Title: 'AI- ఆధారిత ప్రశ్నలు',
        feature1Desc: 'నైపుణ్యాలు మరియు అనుభవాన్ని కచ్చితంగా అంచనా వేసే సంబంధిత, పాత్ర-నిర్దిష్ట ప్రశ్నలను రూపొందించండి.',
        feature2Title: 'నిష్పాక్షిక మూల్యాంకనం',
        feature2Desc: 'ముఖ్యమైన వాటిపై దృష్టి పెట్టండి. మా AI ఆబ్జెక్టివ్ ఫీడ్‌బ్యాక్‌ను అందిస్తుంది, మానవ పక్షపాతాన్ని తగ్గిస్తుంది.',
        feature3Title: 'లోతైన రిపోర్టింగ్',
        feature3Desc: 'స్పష్టమైన కొలమానాలు మరియు సారాంశాలతో అభ్యర్థి పనితీరుపై వివరణాత్మక నివేదికలను పొందండి.',
        interviewSetupTitle: 'AI ఇంటర్వ్యూ సెటప్',
        pasteResume: 'మీ పునఃప్రారంభం వచనాన్ని ఇక్కడ అతికించండి...',
        jobRolePlaceholder: 'మీరు దరఖాస్తు చేస్తున్న ఉద్యోగ పాత్రను నమోదు చేయండి...',
        parseResume: 'పునఃప్రారంభం విశ్లేషించి & ప్రారంభించండి',
        analyzing: 'మీ పునఃప్రారంభం విశ్లేషిస్తోంది...',
        skillsReview: 'మీ నైపుణ్యాల సమీక్ష',
        skillsReviewDesc: 'మేము మీ పునఃప్రారంభం విశ్లేషించాము. ఇంటర్వ్యూ ప్రారంభించే ముందు మేము గుర్తించిన నైపుణ్యాలను దయచేసి సమీక్షించండి.',
        interviewInProgress: 'ఇంటర్వ్యూ పురోగతిలో ఉంది',
        yourAnswer: 'మీ సమాధానాన్ని ఇక్కడ టైప్ చేయండి...',
        interviewComplete: 'ఇంటర్వ్యూ పూర్తయింది!',
        interviewCompleteDesc: 'ఇంటర్వ్యూని పూర్తి చేసినందుకు ధన్యవాదాలు. మేము ఇప్పుడు మీ వివరణాత్మక నివేదికను రూపొందిస్తున్నాము.',
        role: 'పాత్ర',
        candidate: 'అభ్యర్థి',
        hrAdmin: 'హెచ్‌ఆర్ / రిక్రూటర్',
        accountCreatedSuccess: 'ఖాతా సృష్టించబడింది! మీరు ఇప్పుడు లాగిన్ చేయవచ్చు.',
        forgotPassword: 'పాస్‌వర్డ్ మర్చిపోయారా?',
        resetPassword: 'పాస్‌వర్డ్‌ను రీసెట్ చేయండి',
        resetPasswordInstruction: 'రీసెట్ లింక్‌ను స్వీకరించడానికి మీ ఇమెయిల్‌ను నమోదు చేయండి.',
        sendResetLink: 'రీసెట్ లింక్‌ను పంపండి',
        checkEmailForReset: 'రీసెట్ లింక్ కోసం మీ ఇమెయిల్‌ను తనిఖీ చేయండి.',
        backToLogin: 'లాగిన్‌కు తిరిగి వెళ్ళు',
        setNewPassword: 'కొత్త పాస్‌వర్డ్‌ను సెట్ చేయండి',
        enterNewPassword: 'క్రింద మీ కొత్త పాస్‌వర్డ్‌ను నమోదు చేయండి.',
        newPassword: 'కొత్త పాస్వర్డ్',
        confirmNewPassword: 'కొత్త పాస్‌వర్డ్‌ను నిర్ధారించండి',
        passwordsDoNotMatch: 'పాస్‌వర్డ్‌లు సరిపోలడం లేదు.',
        passwordUpdatedSuccess: 'పాస్‌వర్డ్ విజయవంతంగా నవీకరించబడింది!',
        updatePassword: 'పాస్‌వర్డ్‌ను నవీకరించండి',
    },
    fr: {
        login: 'Connexion',
        logout: 'Déconnexion',
        homeTitle: 'Des entretiens plus justes, de meilleures embauches',
        homeSubtitle: 'Notre plateforme basée sur l\'IA propose des entretiens structurés et impartiaux pour vous aider à identifier les meilleurs talents, sans préjugés.',
        startInterview: 'Commencer mon entretien',
        viewHRDashboard: 'Voir le tableau de bord RH',
        feature1Title: 'Questions basées sur l\'IA',
        feature1Desc: 'Générez des questions pertinentes et spécifiques au poste qui évaluent avec précision les compétences et l\'expérience.',
        feature2Title: 'Évaluation impartiale',
        feature2Desc: 'Concentrez-vous sur ce qui compte. Notre IA fournit des commentaires objectifs, réduisant les biais humains.',
        feature3Title: 'Rapports approfondis',
        feature3Desc: 'Obtenez des rapports détaillés sur les performances des candidats, avec des mesures et des résumés clairs.',
        interviewSetupTitle: 'Configuration de l\'entretien IA',
        pasteResume: 'Collez le texte de votre CV ici...',
        jobRolePlaceholder: 'Entrez le poste pour lequel vous postulez...',
        parseResume: 'Analyser le CV et commencer',
        analyzing: 'Analyse de votre CV...',
        skillsReview: 'Examen de vos compétences',
        skillsReviewDesc: 'Nous avons analysé votre CV. Veuillez passer en revue les compétences que nous avons identifiées avant de commencer l\'entretien.',
        interviewInProgress: 'Entretien en cours',
        yourAnswer: 'Tapez votre réponse ici...',
        interviewComplete: 'Entretien terminé !',
        interviewCompleteDesc: 'Merci d\'avoir terminé l\'entretien. Nous générons maintenant votre rapport détaillé.',
        role: 'Rôle',
        candidate: 'Candidat',
        hrAdmin: 'RH / Recruteur',
        accountCreatedSuccess: 'Compte créé ! Vous pouvez maintenant vous connecter.',
        forgotPassword: 'Mot de passe oublié ?',
        resetPassword: 'Réinitialiser le mot de passe',
        resetPasswordInstruction: 'Entrez votre e-mail pour recevoir un lien de réinitialisation.',
        sendResetLink: 'Envoyer le lien de réinitialisation',
        checkEmailForReset: 'Vérifiez votre e-mail pour le lien de réinitialisation.',
        backToLogin: 'Retour à la connexion',
        setNewPassword: 'Définir un nouveau mot de passe',
        enterNewPassword: 'Entrez votre nouveau mot de passe ci-dessous.',
        newPassword: 'Nouveau mot de passe',
        confirmNewPassword: 'Confirmer le nouveau mot de passe',
        passwordsDoNotMatch: 'Les mots de passe ne correspondent pas.',
        passwordUpdatedSuccess: 'Mot de passe mis à jour avec succès !',
        updatePassword: 'Mettre à jour le mot de passe',
    },
    de: {
        login: 'Anmelden',
        logout: 'Abmelden',
        homeTitle: 'Fairere Interviews, bessere Einstellungen',
        homeSubtitle: 'Unsere KI-gestützte Plattform bietet unvoreingenommene, strukturierte Interviews, um Ihnen zu helfen, die besten Talente ohne Vorurteile zu identifizieren.',
        startInterview: 'Mein Interview starten',
        viewHRDashboard: 'HR-Dashboard anzeigen',
        feature1Title: 'KI-gestützte Fragen',
        feature1Desc: 'Generieren Sie relevante, rollenspezifische Fragen, die Fähigkeiten und Erfahrungen genau bewerten.',
        feature2Title: 'Unvoreingenommene Bewertung',
        feature2Desc: 'Konzentrieren Sie sich auf das Wesentliche. Unsere KI gibt objektives Feedback und reduziert menschliche Voreingenommenheit.',
        feature3Title: 'Detaillierte Berichterstattung',
        feature3Desc: 'Erhalten Sie detaillierte Berichte über die Leistung der Kandidaten mit klaren Metriken und Zusammenfassungen.',
        interviewSetupTitle: 'KI-Interview-Setup',
        pasteResume: 'Fügen Sie hier Ihren Lebenslauftext ein...',
        jobRolePlaceholder: 'Geben Sie die Berufsbezeichnung ein, für die Sie sich bewerben...',
        parseResume: 'Lebenslauf analysieren & starten',
        analyzing: 'Analysiere deinen Lebenslauf...',
        skillsReview: 'Überprüfung Ihrer Fähigkeiten',
        skillsReviewDesc: 'Wir haben Ihren Lebenslauf analysiert. Bitte überprüfen Sie die von uns identifizierten Fähigkeiten, bevor Sie mit dem Interview beginnen.',
        interviewInProgress: 'Interview läuft',
        yourAnswer: 'Geben Sie hier Ihre Antwort ein...',
        interviewComplete: 'Interview abgeschlossen!',
        interviewCompleteDesc: 'Vielen Dank für das Ausfüllen des Interviews. Wir erstellen jetzt Ihren detaillierten Bericht.',
        role: 'Rolle',
        candidate: 'Kandidat',
        hrAdmin: 'Personal / Recruiter',
        accountCreatedSuccess: 'Konto erstellt! Sie können sich jetzt anmelden.',
        forgotPassword: 'Passwort vergessen?',
        resetPassword: 'Passwort zurücksetzen',
        resetPasswordInstruction: 'Geben Sie Ihre E-Mail-Adresse ein, um einen Link zum Zurücksetzen zu erhalten.',
        sendResetLink: 'Link zum Zurücksetzen senden',
        checkEmailForReset: 'Überprüfen Sie Ihre E-Mails auf den Link zum Zurücksetzen.',
        backToLogin: 'Zurück zur Anmeldung',
        setNewPassword: 'Neues Passwort festlegen',
        enterNewPassword: 'Geben Sie unten Ihr neues Passwort ein.',
        newPassword: 'Neues Passwort',
        confirmNewPassword: 'Neues Passwort bestätigen',
        passwordsDoNotMatch: 'Passwörter stimmen nicht überein.',
        passwordUpdatedSuccess: 'Passwort erfolgreich aktualisiert!',
        updatePassword: 'Passwort aktualisieren',
    },
    zh: {
        login: '登录',
        logout: '登出',
        homeTitle: '更公平的面试，更好的招聘',
        homeSubtitle: '我们的人工智能平台提供无偏见、结构化的面试，帮助您识别最优秀的人才，不受偏见影响。',
        startInterview: '开始我的面试',
        viewHRDashboard: '查看人力资源仪表板',
        feature1Title: '人工智能驱动的问题',
        feature1Desc: '生成相关的、针对特定职位的问题，准确评估技能和经验。',
        feature2Title: '无偏见评估',
        feature2Desc: '专注于重要的事情。我们的人工智能提供客观的反馈，减少人为偏见。',
        feature3Title: '深入报告',
        feature3Desc: '获取有关候选人表现的详细报告，其中包含清晰的指标和摘要。',
        interviewSetupTitle: 'AI 面试设置',
        pasteResume: '在此处粘贴您的简历文本...',
        jobRolePlaceholder: '输入您申请的职位...',
        parseResume: '分析简历并开始',
        analyzing: '正在分析您的简历...',
        skillsReview: '您的技能审查',
        skillsReviewDesc: '我们已经分析了您的简历。在开始面试之前，请查看我们确定的技能。',
        interviewInProgress: '面试进行中',
        yourAnswer: '在此处输入您的答案...',
        interviewComplete: '面试完成！',
        interviewCompleteDesc: '感谢您完成面试。我们现在正在生成您的详细报告。',
        role: '角色',
        candidate: '候选人',
        hrAdmin: '人力资源 / 招聘人员',
        accountCreatedSuccess: '帐户已创建！您现在可以登录了。',
        forgotPassword: '忘记密码？',
        resetPassword: '重设密码',
        resetPasswordInstruction: '输入您的电子邮件以接收重置链接。',
        sendResetLink: '发送重置链接',
        checkEmailForReset: '请检查您的电子邮件以获取重置链接。',
        backToLogin: '返回登录',
        setNewPassword: '设置新密码',
        enterNewPassword: '在下方输入您的新密码。',
        newPassword: '新密码',
        confirmNewPassword: '确认新密码',
        passwordsDoNotMatch: '密码不匹配。',
        passwordUpdatedSuccess: '密码更新成功！',
        updatePassword: '更新密码',
    },
};