
import React from 'react';
import { motion } from 'framer-motion';
import { Interview } from '../types';

const ExplainDecisionModal = ({ interview }: { interview: Interview }) => {

    const avgConfidence = interview.confidence_scores && interview.confidence_scores.length > 0
        ? Math.round(interview.confidence_scores.reduce((a, b) => a + b, 0) / interview.confidence_scores.length)
        : 0;

    return (
        <motion.div 
            initial={{ opacity: 0, scale: 0.95 }}
            animate={{ opacity: 1, scale: 1 }}
            className="p-4"
        >
            <h2 className="text-2xl font-bold text-text-primary">AI Decision Explanation</h2>
            <p className="text-sm text-text-secondary mb-4">For candidate: {interview.candidate_name}</p>

            <div className="grid grid-cols-2 gap-4 mb-4 text-center">
                <div className="bg-muted-background p-3 rounded-lg">
                    <p className="text-sm text-text-secondary">Predicted Fit Score</p>
                    <p className="text-2xl font-bold text-brand-primary">{interview.overall_score}%</p>
                </div>
                 <div className="bg-muted-background p-3 rounded-lg">
                    <p className="text-sm text-text-secondary">Confidence Level</p>
                    <p className="text-2xl font-bold">{avgConfidence}%</p>
                </div>
            </div>
            
            <div>
                <h3 className="font-semibold mb-2">Fairness Explanation:</h3>
                <div className="text-sm bg-muted-background p-3 rounded-lg text-text-secondary space-y-2">
                   <p>{interview.summary}</p>
                   <p className="text-xs italic opacity-70">This explanation is generated by an LLM to provide insight into the model's decision-making process. It is based on the key factors the model considered most important.</p>
                </div>
            </div>
        </motion.div>
    );
};

export default ExplainDecisionModal;